### ISSUE TITLE
Menu Example

### ISSUE THREAD

**Issue by Glockko** [LemonUIbyLemon/LemonUI#70]
Could you please add a Menu Example like in https://github.com/FrazzIe/NativeUILua ?

Guad's NativeUI had one but his doesn't include a fxmanifest.lua and unfortunately I don't know C# at all therefore an example would be a massive help and I would be eternally grateful.

**Comment by justalemon** [comment]
There were examples, but they were removed due to being convoluted and hard to read (it was a single script that targeted the then 4 available frameworks, [you can check it out here](https://github.com/LemonUIbyLemon/LemonUI/blob/f13208165a75409fac51265775bb10ea33fdcf32/LemonUI.Example/Demo.cs)). Now that there is an organization, we could probably make a new repository with the whole purpose of storing different types of examples.

**Comment by Glockko** [comment]
Many thanks, I look forward to it.

**Comment by justalemon** [comment]
There is now https://github.com/LemonUIbyLemon/Examples

**Comment by Glockko** [comment]
Thank you
